### ISSUE TITLE
signer not match

### ISSUE THREAD

**Issue by yclinhh** [woshisad159/TFNet#3]
Why do the signers in the dataset not correspond to the signers in the labels?

**Comment by woshisad159** [comment]
Please give me an actual example so I can answer you.


------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "woshisad159/TFNet"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2024年11月27日(星期三) 中午11:16
***@***.***&gt;;
***@***.***&gt;;
主题:&nbsp;[woshisad159/TFNet] signer not match (Issue #3)





 
Why do the signers in the dataset not correspond to the signers in the labels?

**Comment by yclinhh** [comment]
For example, the serial number of the video in the directory  /train/I/     is from train-03710 to train-03775, but the serial number of the translator I in the train.csv file is from train-03966 to train-04466.

**Comment by woshisad159** [comment]
I have understood the problem, this is the label version problem, now uploaded is the old version of the label, the personnel number H backward corresponds to the problem, the follow-up I will upload a new version of the label, but this problem does not affect the program running results, because the program is through the front of the serial number to correspond to the label, for example: train-03775 video, corresponding to the For example: the video of train-03775 corresponds to the label of train-03775.






------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "woshisad159/TFNet"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2024年11月27日(星期三) 下午2:22
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [woshisad159/TFNet] signer not match (Issue #3)





 
For example, the serial number of the video in the directory  /train/I/     is from train-03710 to train-03775, but the serial number of the translator I in the train.csv file is from train-03966 to train-04466.

**Comment by woshisad159** [comment]
I have understood the problem, this is the label version problem, now uploaded is the old version of the label, the personnel number H backward corresponds to the problem, the follow-up I will upload a new version of the label, but this problem does not affect the program running results, because the program is through the front of the serial number to correspond to the label, For example: the video of train-03775 corresponds to the label of train-03775.




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "woshisad159/TFNet"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2024年11月27日(星期三) 下午2:22
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [woshisad159/TFNet] signer not match (Issue #3)





 
For example, the serial number of the video in the directory  /train/I/     is from train-03710 to train-03775, but the serial number of the translator I in the train.csv file is from train-03966 to train-04466.

**Comment by yclinhh** [comment]
ok, thanks a lot for answering my question
